#pragma once

#include "board_config.h"

#define KMYC_TOUCH_I2C_PORT KMYC_BOARD_I2C_PORT
#define KMYC_TOUCH_I2C_SCL_GPIO KMYC_BOARD_I2C_SCL_GPIO
#define KMYC_TOUCH_I2C_SDA_GPIO KMYC_BOARD_I2C_SDA_GPIO
#define KMYC_TOUCH_I2C_SPEED_HZ 400000
#define KMYC_TOUCH_I2C_TIMEOUT_MS 100
#define KMYC_TOUCH_STARTUP_DELAY_MS 200
#define KMYC_TOUCH_PRIMARY_ADDRESS 0x5D
#define KMYC_TOUCH_BACKUP_ADDRESS 0x14
#define KMYC_TOUCH_OUTPUT_WIDTH 800
#define KMYC_TOUCH_OUTPUT_HEIGHT 1280
#define KMYC_TOUCH_SWAP_XY 1
#define KMYC_TOUCH_MIRROR_X 1
#define KMYC_TOUCH_MIRROR_Y 0
